### ISSUE TITLE
Conda install gnuradio fails: PackagesNotFoundError 

### ISSUE THREAD

**Issue by robisen1** [ryanvolz/gnuradio-feedstock-orig#2]
When trying to install gnuradio to use with python I get 

(signalenv) C:\Users\robis>conda config --add channels ryanvolz

(signalenv) C:\Users\robis>conda install gnuradio
Collecting package metadata: done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - gnuradio

Current channels:

  - https://conda.anaconda.org/ryanvolz/win-64
  - https://conda.anaconda.org/ryanvolz/noarch
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/win-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**Comment by ryanvolz** [comment]
Yeah, it's unfortunate but getting gnuradio to build within the anaconda/conda-forge ecosystem is a challenge, especially for Windows. In fact, I've never been successful with Windows yet. Recently I've been trying to get the unreleased 3.8 branch to work because it can use python 3 and does away with some older dependencies, and I'm getting close. I'll leave this issue open and comment when I'm finally successful.

Additionally, you'd need to also add the conda-forge channel because this package builds off of that ecosystem. But that won't do any good until I actually have a package you can install.

**Comment by robisen1** [comment]
Thanks.i did add the condado forge. I have gotten GNU to work in the post
on windows but what a pain. Thanks for your quick response

**Comment by ryanvolz** [comment]
There's now a Windows build that works with Python 3. Unfortunately it doesn't include gnuradio-companion since conda doesn't have a gtk3 package. Hopefully that will change at some point in the future. In the limited testing I've done, the rest looks to be in pretty good shape.

Since it's a prerelease version of GNU Radio 3.8, it's only available on my prerelease channel. You'll have to do `conda config --add channels ryanvolz/label/prerelease` or run `conda install` with `-c ryanvolz/label/prerelease` to find it.

**Comment by ryanvolz** [comment]
GNU Radio is now on [conda-forge](https://github.com/conda-forge/gnuradio-feedstock), including a Windows release for version 3.8.0.
