### ISSUE TITLE
OSx and OOT modules

### ISSUE THREAD

**Issue by cpbridges** [ryanvolz/gnuradio-feedstock-orig#3]
Before I start installation - can this conda port install OOT modules? E.g. gr-satellites?

This would be amazing if it's possible. Best, Chris

**Comment by ryanvolz** [comment]
First, I'm not sure about the overall state of health of this package on OSX right now. I've been getting test errors from the build bot and haven't tracked down a cause since I personally run linux, so you might run into issues. If you do, please report any details and I can try to fix it.

Second, I don't see any reason that a third party module wouldn't work, but I think you would have to compile against the conda package and have it install within the conda ecosystem. You could take a look at the build.sh script within this recipe for clues about how to set CMake variables to make it work. It might be just as easy to create a conda package for the third party module, since that's essentially automating what you'd be doing with a manual build. Good luck, and feel free to comment on how it goes!

**Comment by ryanvolz** [comment]
GNU Radio is now on [conda-forge](https://github.com/conda-forge/gnuradio-feedstock), so it now should be much easier to add and support OOT modules over there. Please raise the issue over there if you're still interested!
